### PR TITLE
Trying to fix CF isssue

### PR DESCRIPTION
**Pull request by procrastinatio**
Updated the httplib to Apache HttpClient 4.5.3 and trying to make the code work (but I really don't know what I am doing)

It may fix some of these https://github.com/geoadmin/service-print/issues/29

Use: `print_url=//service-print.int.bgdi.ch/mom_cf_fix` with an old mf-geoadmin, e.g. `master/057c288/1701251212/index.html` which does not have all ugly hacks.

https://map.geo.admin.ch/master/057c288/1701251212/index.html?print_url=//service-print.int.bgdi.ch/mom_cf_fix

1/ KML 
[Demo, with KML, with fix](https://map.geo.admin.ch/master/057c288/1701251212/index.html?print_url=//service-print.int.bgdi.ch/mom_cf_fix&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FrmWZSgtGQ-u7vpqQ7Z8djQ&layers_visibility=true)

[Demo, with KML,  without fix](https://map.geo.admin.ch/?layers=KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FrmWZSgtGQ-u7vpqQ7Z8djQ)

2/ Marker
Try with: https://map.geo.admin.ch/master/057c288/1701251212/index.html?print_url=//service-print.int.bgdi.ch/mom_cf_fix
 * Search for 'Versoix'
 * Print Versoix and the red marker
 * PDF has a nice red marker 

:bomb: Jenkins fails, because there is no tomcat on jenkins (same instance as vpc-mf1-dev-1), we are on vpc-mf0-dev1

Hopefully cléeanly fixes:
  * https://github.com/geoadmin/mf-geoadmin3/issues/3814
  * https://github.com/geoadmin/mf-geoadmin3/issues/3812
  * https://github.com/geoadmin/mf-geoadmin3/issues/3808
  * https://github.com/geoadmin/mf-geoadmin3/issues/3794

### CODE REVIEW

**Comment by gjn** [comment]
From which version to which version was the httpclient update?

**Comment by procrastinatio** [comment]
from 'commons-httpclient:commons-httpclient:3.1' (>10 years, final) to     'org.apache.httpcomponents:httpclient:4.5.3' (< 1 month)

Diff
https://github.com/mapfish/mapfish-print/compare/2.1.x...procrastinatio:mom_fix_cf

**Review by loicgasser — COMMENTED** [review]
We have 2 print-servlet-2.1.3-SNAPSHOT.war now in the project.
one at the base and the other the tomcat folder.

**Comment by loicgasser** [comment]
The PR was failing on Jenkins legacy, yes we still have one.

See:

https://jenkins.prod.bgdi.ch/job/PR_print_service/

We don't have anything on Jenkins Jessie for the print service.
See: https://jenkins.ci.bgdi.ch/

**Pull request merged**
