### PR TITLE
Migrate to ALB

### PR DESCRIPTION
**Pull request by loicgasser**

### CODE REVIEW

**Comment by loicgasser** [comment]
Fix for https://github.com/geoadmin/service-print/issues/77

**Comment by danduk82** [comment]
the config seems good to me. Is this deploying directly to dev with jenkins ?

**Review by danduk82 — APPROVED** [review]
lgtm

**Comment by loicgasser** [comment]
yes

**Comment by loicgasser** [comment]
it's on dev

**Comment by danduk82** [comment]
god a multiprint is slow on dev (scale 1:1000).

**Comment by loicgasser** [comment]
it's not working.

**Comment by danduk82** [comment]
ah

**Comment by loicgasser** [comment]
I think I need to pass the hostname.

**Comment by loicgasser** [comment]
we don't need the port anymore,  but we do need the hostname

**Pull request merged**
