### PR TITLE
Format A6 (postcard)

### PR DESCRIPTION
**Pull request by procrastinatio**
Add support for a postcard-like PDF (DIN A6)

See https://github.com/geoadmin/service-print/issues/109

[lv95_simple_a6_v11.pdf](https://github.com/geoadmin/service-print/files/4775153/lv95_simple_a6_v11.pdf)

### CODE REVIEW

**Comment by davidoesch** [comment]
Mockup : https://docs.google.com/presentation/d/1Z3luQKw-fq43zp5N6MNSsc3bWbzlLpKiKyEynvB-NvU/edit#slide=id.p 

image

What dou you think @procrastinatio - doable?

**Comment by p1d1d1** [comment]
„n“ can get too long and you could have several „@„
Maybe link to colophon would be enough?

**Comment by davidoesch** [comment]
image
 with copyrights on the right https://docs.google.com/presentation/d/1Z3luQKw-fq43zp5N6MNSsc3bWbzlLpKiKyEynvB-NvU/edit#slide=id.g88d6976a43_0_0

@procrastinatio hope this is ok from your perspective

**Comment by procrastinatio** [comment]
@davidoesch 
https://map.geo.admin.ch/?print_url=//service-print.dev.bgdi.ch (if no A6, cache issue)

Limitations: map margins are big, can't do much, no text rotation, used ' •' instead of '|' (can't escape this in YAML!), QRcode should not be too small, otherwise it fails.

lv95_stundensteine_a6-1

Corresponding PDF [lv95_stundensteine_a6.pdf](https://github.com/geoadmin/service-print/files/4776840/lv95_stundensteine_a6.pdf)

**Comment by davidoesch** [comment]
- [x] scale denominator : 1:50'000 instead of 1:50000 etc
- [x] logo and qr are still quite big 75% of QR could still be opened with my vintage iphone 7 , logo height size can then be reduced as well.

margin: we have to live with it

**Comment by procrastinatio** [comment]
lv95_simple_a6_de jpg-1

[lv95_simple_a6_de.pdf](https://github.com/geoadmin/service-print/files/4777119/lv95_simple_a6_de.pdf)

**Comment by davidoesch** [comment]
looks better and better
put the confederatio helvetica logo all the way down, same height as QR, possible?
text "geo.admin.ch etc" on the right of the logo?

**Comment by procrastinatio** [comment]
https://map.geo.admin.ch/?print_url=//service-print.dev.bgdi.ch (if no A6, cache issue)

lv95_a6_murten_rotated_v20 jpg-1

(from [lv95_a6_murten_rotated.pdf](https://github.com/geoadmin/service-print/files/4778302/lv95_a6_murten_rotated.pdf)

**Comment by davidoesch** [comment]
- [x] replace "Source"  with (c)  as in  the other formats

**Comment by procrastinatio** [comment]
@davidoesch  OK, same as other formats (the (c) is sent by the client though)

**Comment by procrastinatio** [comment]
@davidoesch OK? Merge? Deploy?

**Comment by davidoesch** [comment]
and deploy ! thx Marc

**Comment by davidoesch** [comment]
ups I merged to master --sorry

**Comment by procrastinatio** [comment]
@davidoesch OK deployed

**Pull request merged**
