### PR TITLE
Validating vector geometries from spec file

### PR DESCRIPTION
**Pull request by procrastinatio**
See https://github.com/geoadmin/mf-geoadmin3/issues/3714

### CODE REVIEW

**Comment by gjn** [comment]
Any testlink?

**Comment by procrastinatio** [comment]
No, won't because, because it relies on features develops for print v3 and never commited back to printv2.

**Comment by procrastinatio** [comment]
Rebase

**Comment by ltkum** [comment]
I think it is safe to close this now.

**Pull request closed without merging**
