### PR TITLE
Adapt scripts, tests, cleanup and variables

### PR DESCRIPTION
**Pull request by loicgasser**
pping @procrastinatio @gjn 

This PR is for print_v2 branch

I did not test the deploy scripts yet. To do tomorrow when we merge.

### CODE REVIEW

**Comment by procrastinatio** [comment]
In `Makefile`, `printconfig`and `printwar`should be called, maybe in target `all`, otherwise nothing is installed in the tomcat dir.

**Comment by procrastinatio** [comment]
Branch management and snapshot is a bit overkill, but otherwise OK for me.

We mail merge rapidly, this is not used anywhere for now.

**Comment by gjn** [comment]
@loicgasser Thanks for the effort!

Please assure that we don't loose the work done for print **v3**. So IMO, we can merge this into v2 branch, then we should branch out v3 code from master and merge v2 branch into master.

Ok?

**Comment by loicgasser** [comment]
yes we discussed it. We'll tag it and backup the zip file, as well as a local backup.

**Pull request merged**
