### PR TITLE
Using MapFish print v2

### PR DESCRIPTION
**Pull request by procrastinatio**
Using config, printproxy and war files from mf-chsdi3.

[GET /print/info.json](http://service-print.dev.bgdi.ch/print/info.json)
[POST /print/create.json](http://service-print.dev.bgdi.ch/print/create.json)

idem for [int](http://service-print.int.bgdi.ch/print/info.json) and [prod](http://service-print.prod.bgdi.ch/print/info.json)

For production, the addresse is [print.geo.admin.ch](https://print.geo.admin.ch/print/info.json) (forced into https)

### CODE REVIEW

**Comment by loicgasser** [comment]
What do we do about the profile and height services ? We ll have to leave them here for now.

**Comment by gjn** [comment]
This project is for print.

**Comment by loicgasser** [comment]
We propose to create `service-alti` for profile and height services which will be deployed on stateless instances as well.

**Comment by loicgasser** [comment]
Ok my take on this is that you can remove all that is useless.

Restart with a fresh git history -> commit one and adpat readme (it seems that most of it has been done already though)
and so on.
we should end up with a micro application.

**Comment by loicgasser** [comment]
Remove

some of https://github.com/geoadmin/service-print/tree/master/print3/tests
https://github.com/geoadmin/service-print/blob/master/scripts/rssFeedGen.py
https://github.com/geoadmin/service-print/blob/master/scripts/build.sh
https://github.com/geoadmin/service-print/tree/master/translations

Variable clean up in https://github.com/geoadmin/service-print/blob/master/rc_dev and other rc files.

Adapt https://github.com/geoadmin/service-print/blob/master/print3/__init__.py#L30

no more models

**Comment by gjn** [comment]
I agree, cleanup would make sense.

**Comment by loicgasser** [comment]
ok cleaning up

**Comment by procrastinatio** [comment]
The Print V3 is in the follwing release https://github.com/geoadmin/service-print/releases/tag/v3.0-alpha

**Comment by loicgasser** [comment]
Shall I apply the cleanup commit to print v3 as well?

**Comment by gjn** [comment]
Not needed now.

**Comment by procrastinatio** [comment]
@loicgasser Print v3 is dead for now.

**Comment by procrastinatio** [comment]
We may merge this one into `master` and deploy.

**Comment by loicgasser** [comment]
Jekins would be good as well

**Comment by gjn** [comment]
what tests could be run.

**Comment by loicgasser** [comment]
well the build and lint to start with
and also a couple here:
https://github.com/geoadmin/service-print/tree/master/print3/tests

**Comment by loicgasser** [comment]
At least for new PRs.

**Comment by gjn** [comment]
I can have a look.

sidenote: print3 is wrong folder name.

**Comment by loicgasser** [comment]
I know but in the end it makes sense with geoadmin3, chsdi3 etc..

**Comment by procrastinatio** [comment]
'print' is a reserved word in python, so it cannot be used as a module
name, hence the 'print3'.

**Comment by loicgasser** [comment]
that too, I guess he was thinking of print2

**Comment by gjn** [comment]
@procrastinatio @loicgasser is it deployed on all stages? If so, please also create a release in github.

**Pull request merged**
