### PR TITLE
Add a better image for north icon

### PR DESCRIPTION
**Pull request by oterral**
[test](http://mf-geoadmin3.dev.bgdi.ch/ltteo/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&zoom=1&dev3d=true&debug)

### CODE REVIEW

**Comment by gjn** [comment]
+1!

**Comment by loicgasser** [comment]
oh we should deploy that.

**Comment by gjn** [comment]
Yep, I've put it in the remember_to_deploy doc ;=)

**Comment by loicgasser** [comment]
yes I saw that, I was concerned by other matters. :o

**Comment by procrastinatio** [comment]
You could and should deploy it independently from the rest. It is a **goal** of these _microservices_

**Pull request merged**
